budgeting_app/app/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'app'

urlpatterns = [
    path('', views.dashboard_view, name="dashboard"),
    path('dashboard-delete-transactions', csrf_exempt(views.dashboard_delete_transactions), name="dashboard_delete_transactions"),
    path('dashboard-get-categories', csrf_exempt(views.dashboard_get_categories), name="dashboard_get_categories"),
    path('dashboard-edit-transaction', views.dashboard_edit_transaction, name="dashboard_edit_transaction"),
    path('dashboard-get-chart', csrf_exempt(views.dashboard_get_chart), name="dashboard_get_chart"),
    path('transactions/', views.transactions_view, name="transactions"),
    path('categories/', views.categories_view, name="categories"),
    path('summaries/', views.summaries_view, name="summaries"),
    path('create-category', csrf_exempt(views.create_category), name="create_category"),
    path('edit-category', csrf_exempt(views.edit_category), name="edit_category"),
    path('delete-category', csrf_exempt(views.delete_category), name="delete_category"),
    path('edit-budget', csrf_exempt(views.edit_budget), name="edit_budget"),
    path('get-budget', csrf_exempt(views.get_budget), name="get_budget"),
    path('set-date-range', csrf_exempt(views.set_date_range), name="set_date_range"),
    path('get-pie-chart', csrf_exempt(views.get_pie_chart), name="get_pie_chart"),
    path('set-sort-date', csrf_exempt(views.set_sort_date), name="set_sort_date"),
    path('set-sort-amount', csrf_exempt(views.set_sort_amount), name="set_sort_amount"),
    path('search-transactions', csrf_exempt(views.search_transactions), name="search_transactions"),
    path('get-expenses', csrf_exempt(views.get_expenses), name="get_expenses"),
    path('settings', views.settings_view, name="settings"),
    path('get-rates', csrf_exempt(views.get_rates), name="get_rates"),
    path('change-pfp', csrf_exempt(views.change_pfp), name="change_pfp"),
    path('delete_user', views.delete_user, name="delete_user"),
    path('export-csv', views.export_csv, name="export_csv"),
]

budgeting_app/budgeting_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('app/', include("app.urls")),
    path('users/', include("users.urls")),
]

budgeting_app/app/templates/app/dashboard.html
{% extends 'app/layout.html' %}
{% load humanize %}
{% load static %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<main class="main px-md-5">
    {% include 'partials/_messages.html' %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-4">
        <h1 class="fs-4">Dashboard</h1>
    </div>
    <div class="pb-1 mb-2 border-bottom">
        <p></p>
    </div>

    <div class="mt-4 mb-4 d-flex justify-content-between align-items-center">
        <h2 class="fs-5">Overview</h2>
        <div class="dates d-flex gap-2">
            <button id="todayBtn" class="btn {% if selected_date == 'today' %} btn-secondary {% else %} btn-outline-secondary {% endif %}">Today</button>
            <button id="weekBtn" class="btn {% if selected_date == 'week' %} btn-secondary {% else %} btn-outline-secondary {% endif %}">This week</button>
            <button id="monthBtn" class="btn {% if selected_date == 'month' %} btn-secondary {% else %} btn-outline-secondary {% endif %}">This month</button>
            <button id="yearBtn" class="btn {% if selected_date == 'year' %} btn-secondary {% else %} btn-outline-secondary {% endif %}">This year</button>
        </div>
    </div>

    <div class="d-flex flex-column flex-lg-row gap-4">
        <div class="cards">
            <div class="card mb-4 shadow-sm p-2" style="width: 100%;">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start mb-3">
                        <div>
                            <h5 class="card-title fs-6 text-secondary mb-3">TOTAL BALANCE</h5>
                            <p class="card-text fs-3 fw-semibold" id="totalBalance"></p>
                        </div>
                        <i class="lni lni-coin fs-3 bg_yellow_subtle p-2 rounded text_yellow"></i>
                    </div>
                    <div class="d-flex gap-3">
                        <p class="{% if percentTotal > 0 %}text-success{% elif percentTotal < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if percentTotal > 0 %}lni-angle-double-up{% elif percentTotal < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i> {{ percentTotal }}%</p>
                        <p class="text-secondary fs-6 mb-0">Since {% if selected_date == 'today' %}yesterday{% elif selected_date == 'week' %}last week{% elif selected_date == 'month' %}last month{% else %}last year{% endif %} <span class="text-black-50" id="lastTotal"></span></p>
                    </div>
                </div>
            </div>
            <div class="card mb-4 shadow-sm p-2" style="width: 100%;">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start mb-3">
                        <div>
                            <h2 class="card-title fs-6 text-secondary mb-3">EXPENSES</h2>
                            <p class="card-text fs-3 fw-semibold" id="expenses"></p>
                        </div>
                        <i class="lni lni-stats-down fs-3 bg-danger-subtle p-2 rounded text-danger"></i>
                    </div>
                    <div class="d-flex gap-3">
                        <p class="{% if percentExpenses > 0 %}text-success{% elif percentExpenses < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if percentExpenses > 0 %}lni-angle-double-up{% elif percentExpenses < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i> {{ percentExpenses }}%</p>
                        <p class="text-secondary fs-6 mb-0">Since {% if selected_date == 'today' %}yesterday{% elif selected_date == 'week' %}last week{% elif selected_date == 'month' %}last month{% else %}last year{% endif %} <span class="text-black-50" id="lastExpenses"></span></p>
                    </div>
                </div>
            </div>
            <div class="card shadow-sm p-2" style="width: 100%;">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start mb-3">
                        <div>
                            <h5 class="card-title fs-6 text-secondary mb-3">INCOME</h5>
                            <p class="card-text fs-3 fw-semibold" id="income"></p>
                        </div>
                        <i class="lni lni-stats-up fs-3 bg-success-subtle p-2 rounded text-success"></i>
                    </div>
                    <div class="d-flex gap-3">
                        <p class="{% if percentIncome > 0 %}text-success{% elif percentIncome < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if percentIncome > 0 %}lni-angle-double-up{% elif percentIncome < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i> {{ percentIncome }}%</p>
                        <p class="text-secondary fs-6 mb-0">Since {% if selected_date == 'today' %}yesterday{% elif selected_date == 'week' %}last week{% elif selected_date == 'month' %}last month{% else %}last year{% endif %} <span class="text-black-50" id="lastIncome"></span></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="graph" id="expenseIncomeChart" style="background-color: white; height=auto;"></div>
    </div>

    <div id="recentContainer" class="mt-4 mb-4" style="background-color:white;">
        <div class="pb-4 pt-4 px-4 d-flex justify-content-between align-items-center">
            <div class="d-flex gap-3 align-items-center">
                <h2 class="fs-6 text-secondary">RECENTLY ADDED TRANSACTIONS</h2>
                <button class="btn btn-outline-danger d-none" id="dashboard_delete_transactions">Delete Selection</button>
            </div>
            <div >
                <button type="button" id="quick_add_btn" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#typeModelToggle">Add Transaction</button>
            </div>
        </div>

        <div class="table-responsive px-2">
            <table class="table table-sm">
            <thead class="fs-6">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Type</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Category</th>
                    <th scope="col">Date</th>
                    <th scope="col">Comment</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody class="fs-6">
            {% for transaction in recent_transactions %}
                <tr>
                <td class="align-middle text-left"><input type="checkbox" name="selected_transaction" id="{{ transaction.id }}" value="{{ transaction.id }}"></td>
                <td class="align-middle text-left fw-bold {% if transaction.transaction_type == 'Expense' %}text-danger{% else %}text-success{% endif %}">{{ transaction.transaction_type }}</td>
                <td class="align-middle text-left tableAmount">{{ transaction.amount }}</td>
                <td class="align-middle text-left"><div class="d-flex align-items-center gap-2"><i class="lni {{ transaction.category__icon_tag }}"></i><div>{{ transaction.category__title }}</div></div></td>
                <td class="align-middle text-left">{{ transaction.date|date:"b. d, Y"|capfirst }}</td>
                <td class="align-middle text-left">{{ transaction.comment }}</td>
                <td class="align-middle text-left">
                    <button
                        class="border-0 bg-white"
                        id="edit_transaction"
                        data-bs-toggle="modal"
                        data-bs-target="#editModalToggle"
                        data-bs-id="{{ transaction.id }}"
                        data-bs-type="{{ transaction.transaction_type }}"
                        data-bs-amount="{{ transaction.cleanAmount }}"
                        data-bs-category="{{ transaction.category__title }}"
                        data-bs-date="{{ transaction.date|date:"Y-m-d\\TH:i" }}"
                        data-bs-comment="{{ transaction.comment }}"
                        data-bs-currency="{{ request.user.profile.currency }}"
                    >
                        <i class="lni lni-cog fs-5 mt-2"></i>
                    </button>
                </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
        <a href="{% url 'app:transactions' %}" class="btn btn-outline-primary mb-3 ms-2">View more</a>
    </div>
</main>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", async function () {
        async function initializePage() {
            try {
                const totalBalance = await convertCurrency("{{ request.user.profile.total }}", 'USD', userCurrency);
                document.getElementById('totalBalance').textContent = `${formatCurrency(totalBalance, userCurrency)}`;
                const lastTotal = await convertCurrency("{{ lastTotal }}", 'USD', userCurrency);
                document.getElementById('lastTotal').textContent = `(${formatCurrency(lastTotal, userCurrency)})`;

                const expenses = await convertCurrency("{{ expenses }}", 'USD', userCurrency);
                document.getElementById('expenses').textContent = `${formatCurrency(expenses, userCurrency)}`;
                const lastExpenses = await convertCurrency("{{ lastExpenses }}", 'USD', userCurrency);
                document.getElementById('lastExpenses').textContent = `(${formatCurrency(lastExpenses, userCurrency)})`;

                const income = await convertCurrency("{{ income }}", 'USD', userCurrency);
                document.getElementById('income').textContent = `${formatCurrency(income, userCurrency)}`;
                const lastIncome = await convertCurrency("{{ lastIncome }}", 'USD', userCurrency);
                document.getElementById('lastIncome').textContent = `(${formatCurrency(lastIncome, userCurrency)})`;
            } catch(err) {
                console.error("Error initializing page: ", err);
            }
        }
        initializePage();
    });
</script>
{% endblock %}

budgeting_app/app/templates/app/settings.html
{% extends 'app/layout.html' %}
{% load humanize %}
{% load static %}

{% block title %}
Settings
{% endblock %}

{% block content %}
<main class="main px-md-5">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-4">
        <h1 class="fs-4">Settings</h1>
    </div>
    <div class="pb-1 mb-2 border-bottom">
        <p></p>
    </div>

    {% include 'partials/_delete_account_modal.html' %}

    <div class="card shadow-sm p-2 mt-4" style="width: 100%;">
        <div class="card-body">
            <h5 class="card-title fs-6 fw-normal text-secondary">Change currency:</h5>
            <form action="{% url "app:settings" %}" method="post">
                {% csrf_token %}
                <select class="form-select" id="changeCurrency" name="changeCurrency" aria-label="Change currency">
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                    <option value="MKD">MKD</option>
                </select>
                <button class="btn btn-primary mt-3" style="width: auto;">Save changes</button>
            </form>
        </div>
    </div>
    <div class="card shadow-sm p-2 mt-4" style="width: 100%;">
        <div class="card-body">
            <h5 class="card-title fs-6 fw-normal text-secondary">Change profile picture:</h5>
            <div id="pfpChoices" class="d-flex flex-wrap gap-2 mt-4">
                <img src="https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg" class="rounded-circle" alt="default" style="width:100px; height:100px;" data-bs-url="https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg">
                <img src="https://i.imgur.com/a9G4sTF.png" class="rounded-circle" alt="donkey" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/a9G4sTF.png">
                <img src="https://i.imgur.com/wBQvZFG.png" class="rounded-circle" alt="monkey" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/wBQvZFG.png">
                <img src="https://i.imgur.com/hUnrPAQ.png" class="rounded-circle" alt="hawk" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/hUnrPAQ.png">
                <img src="https://i.imgur.com/siodzVS.png" class="rounded-circle" alt="lemur" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/siodzVS.png">
                <img src="https://i.imgur.com/16BfLwV.png" class="rounded-circle" alt="llama" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/16BfLwV.png">
                <img src="https://i.imgur.com/Agawjmw.png" class="rounded-circle" alt="panther" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/Agawjmw.png">
                <img src="https://i.imgur.com/mBdmQnJ.png" class="rounded-circle" alt="kangaroo" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/mBdmQnJ.png">
                <img src="https://i.imgur.com/Bmeb8CU.png" class="rounded-circle" alt="sloth" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/Bmeb8CU.png">
                <img src="https://i.imgur.com/Im4blnI.png" class="rounded-circle" alt="bunny" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/Im4blnI.png">
                <img src="https://i.imgur.com/4PnvnhA.png" class="rounded-circle" alt="duck" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/4PnvnhA.png">
                <img src="https://i.imgur.com/2SQXRDT.png" class="rounded-circle" alt="penguin" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/2SQXRDT.png">
                <img src="https://i.imgur.com/9Hu9TKS.png" class="rounded-circle" alt="squirrel" style="width:100px; height:100px;" data-bs-url="https://i.imgur.com/9Hu9TKS.png">
            </div>
            <button class="btn btn-primary mt-4" id="savePfp" disabled>Save changes</button>
        </div>
    </div>
    <div class="card shadow-sm p-2 mt-4" style="width: 100%;">
        <div class="card-body">
            <h5 class="card-title fs-6 fw-bold">DANGER ZONE!</h5>
            <p class="text-secondary" style="width:40%;">By deleting your account, you will delete all your transactions and custom categories you've created.</p>
            <button class="btn btn-danger mt-3" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">Delete entire account</button>
        </div>
    </div>
</main>
{% endblock %}

{% block scripts %}
<script>
    const changeCurrency = document.getElementById("changeCurrency");
    changeCurrency.value = userCurrency;
</script>
<script src="{% static 'js/settings.js' %}"></script>
{% endblock %}

budgeting_app/app/templates/app/summaries.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% block title %}
Summaries
{% endblock %}

{% block content %}
<main class="main px-md-5">
    {% include 'partials/_messages.html' %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-4">
        <h1 class="fs-4">Monthly Summaries</h1>
    </div>
    <div class="pb-1 mb-2 border-bottom">
        <p></p>
    </div>

    <div class="d-flex gap-4 mt-4 flex-wrap flex-row justify-content-center">
        <div class="card shadow-sm p-2 border-0 flex-grow-1">
            <div class="card-body">
                <form action="{% url "app:summaries" %}" method="post">
                    {% csrf_token %}
                    <label for="month" class="card-title fs-6 fw-normal text-secondary">Select a month:</label><br>
                    <input type="month" id="month" name="month" class="form-control" value="{{ summary_month }}" max="{{ current_month }}" min="{{ min_month }}" required>
                    <button class="btn btn-primary mt-3" style="width: auto;">See summary</button>
                </form>
            </div>
        </div>
        <div class="card shadow-sm p-2 border-0 flex-grow-1">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-start mb-3">
                    <div>
                        <h5 class="card-title fs-6 text-secondary mb-3">MONTH'S BUDGET</h5>
                        <p class="card-text fs-3 fw-semibold">{{ monthBudget }}</p>
                    </div>
                    <i class="lni lni-coin fs-3 bg_yellow_subtle p-2 rounded text_yellow"></i>
                </div>
                <div class="d-flex gap-3">
                    {% if current_month != summary_month %}
                    <p class="{% if budgetPercent > 0 %}text-success{% elif budgetPercent < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if budgetPercent > 0 %}lni-angle-double-up{% elif budgetPercent < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i>{{ budgetPercent }}%</p>
                    <p class="text-secondary fs-6 mb-0">{% if budgetPercent > 0 %}More than this month{% elif budgetPercent < 0 %}Less than this month{% else %}Same as this month{% endif %} <span class="text-black-50">({{ currBudget }})</span></p>
                    {% else %}
                    <p class="text-secondary text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni lni-minus"></i></p>
                    <p class="text-secondary fs-6 mb-0">Looking at this month</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card shadow-sm p-2 border-0 flex-grow-1">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-start mb-3">
                    <div>
                        <h5 class="card-title fs-6 text-secondary mb-3">SPENT IN MONTH</h5>
                        <p class="card-text fs-3 fw-semibold">{{ sumExpenses }} <span class="text-black-50 fs-6 fw-normal">({{ expensePercentFromBudget }}% of budget)</span></p>
                    </div>
                    <i class="lni lni-stats-down fs-3 bg-danger-subtle p-2 rounded text-danger"></i>
                </div>
                <div class="d-flex gap-3">
                    {% if current_month != summary_month %}
                    <p class="{% if compareMonthsPercentExp > 0 %}text-success{% elif compareMonthsPercentExp < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if compareMonthsPercentExp > 0 %}lni-angle-double-up{% elif compareMonthsPercentExp < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i> {{ compareMonthsPercentExp }}%</p>
                    <p class="text-secondary fs-6 mb-0">{% if compareMonthsPercentExp > 0 %}More than this month{% elif compareMonthsPercentExp < 0 %}Less than this month{% else %}Same as this month{% endif %} <span class="text-black-50">({{ thisMonthExpenses }})</span></p>
                    {% else %}
                    <p class="text-secondary text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni lni-minus"></i></p>
                    <p class="text-secondary fs-6 mb-0">Looking at this month</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card shadow-sm p-2 border-0 flex-grow-1">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-start mb-3">
                    <div>
                        <h5 class="card-title fs-6 text-secondary mb-3">EARNED IN MONTH</h5>
                        <p class="card-text fs-3 fw-semibold">{{ sumIncome }}</p>
                    </div>
                    <i class="lni lni-stats-up fs-3 bg-success-subtle p-2 rounded text-success"></i>
                </div>
                <div class="d-flex gap-3">
                    {% if current_month != summary_month %}
                    <p class="{% if compareMonthsPercentInc > 0 %}text-success{% elif compareMonthsPercentInc < 0 %}text-danger{% else %}text-secondary{% endif %} text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni {% if compareMonthsPercentInc > 0 %}lni-angle-double-up{% elif compareMonthsPercentInc < 0 %}lni-angle-double-down{% else %}lni-minus{% endif %}"></i> {{ compareMonthsPercentInc }}%</p>
                    <p class="text-secondary fs-6 mb-0">{% if compareMonthsPercentInc > 0 %}More than this month{% elif compareMonthsPercentInc < 0 %}Less than this month{% else %}Same as this month{% endif %} <span class="text-black-50">({{ thisMonthIncome }})</span></p>
                    {% else %}
                    <p class="text-secondary text-opacity-75 mb-0 d-flex align-items-center gap-2"><i class="lni lni-minus"></i></p>
                    <p class="text-secondary fs-6 mb-0">Looking at this month</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex flex-lg-row flex-column gap-4 mt-4 mb-4">
        <div class="d-flex flex-column flex-md-row flex-lg-column align-items-center justify-content-between w-lg-25 gap-2">
            <div class="mt-4 chartContainer" style="display: inline-block; background-color: white;">
                <div class="d-flex mt-4 px-4 align-items-center">
                    <h2 class="text-secondary fs-6 w-100">EXPENSES BY CATEGORY</h2>
                </div>
                <div id="pieChartExpense" class="py-4" style="background-color: white;">
                </div>
            </div>
            <div class="mt-4 chartContainer" style="display: inline-block; background-color: white;">
                <div class="d-flex mt-4 px-4 align-items-center">
                    <h2 class="text-secondary fs-6 w-100">INCOME BY CATEGORY</h2>
                </div>
                <div id="pieChartIncome" class="py-4" style="background-color: white;">
                </div>
            </div>
        </div>
        <div class="mt-4 flex-grow-1" id="expenseIncomeChart" style="background-color: white; height:100%;"></div>
    </div>
    <div id="recentContainer" class="mt-4 mb-4" style="background-color:white;">
        <div class="pb-4 pt-4 px-4 d-flex justify-content-between align-items-center">
            <div class="d-flex gap-3 align-items-center">
                <h2 class="fs-6 text-secondary text-nowrap">TRANSACTION HISTORY</h2>
                <input type="text" id="searchInput" class="form-control" placeholder="Search for transactions...">
            </div>
        </div>

        <div class="table-responsive px-4">
            <table class="table table-sm">
            <thead class="fs-6">
                <tr>
                    <th scope="col">Type</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Category</th>
                    <th scope="col">Date</th>
                    <th scope="col">Comment</th>
                </tr>
            </thead>
            <tbody id="transactionsTable" class="fs-6">
            {% for transaction in allTransactions %}
                <tr>
                <td class="py-2 align-middle text-left fw-bold {% if transaction.transaction_type == 'Expense' %}text-danger{% else %}text-success{% endif %}">{{ transaction.transaction_type }}</td>
                <td class="py-2 align-middle text-left tableAmount">{{ transaction.amount }}</td>
                <td class="py-2 align-middle text-left"><div class="d-flex align-items-center gap-2"><i class="lni {{ transaction.category__icon_tag }}"></i><div>{{ transaction.category__title }}</div></div></td>
                <td class="py-2 align-middle text-left">{{ transaction.date|date:"b. d, Y"|capfirst }}</td>
                <td class="py-2 align-middle text-left">{{ transaction.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
            <div class="fs-5 text-secondary py-3 text-center" id="noResults" style="display: none;">No results found</div>
        </div>
    </div>
</main>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
{{ expenseCategoriesKeys|json_script:"expenseCategoriesKeys" }}
{{ expenseCategoriesValues|json_script:"expenseCategoriesValues" }}
{{ incomeCategoriesKeys|json_script:"incomeCategoriesKeys" }}
{{ incomeCategoriesValues|json_script:"incomeCategoriesValues" }}
{{ rangeList|json_script:"rangeList" }}
{{ expenseList|json_script:"expenseList" }}
{{ incomeList|json_script:"incomeList" }}
<script>
    const expenseCategoriesKeys = JSON.parse(document.getElementById('expenseCategoriesKeys').textContent);
    const expenseCategoriesValues = JSON.parse(document.getElementById('expenseCategoriesValues').textContent);
    const incomeCategoriesKeys = JSON.parse(document.getElementById('incomeCategoriesKeys').textContent);
    const incomeCategoriesValues = JSON.parse(document.getElementById('incomeCategoriesValues').textContent);

    const rangeList = JSON.parse(document.getElementById('rangeList').textContent);
    const expenseList = JSON.parse(document.getElementById('expenseList').textContent);
    const incomeList = JSON.parse(document.getElementById('incomeList').textContent);

    $(document).ready(function(){
        $('#searchInput').on('keyup', function() {
            let value = $(this).val().toLowerCase();
            let hasRows = false;

            $('#transactionsTable tr').filter(function() {
                let exists = $(this).text().toLowerCase().indexOf(value) > -1;
                $(this).toggle(exists);
                if(exists) hasRows = true;
            });

            if(hasRows) $('#noResults').hide();
            else $('#noResults').show();
        });
    });
</script>
<script src="{% static 'js/summaries.js' %}"></script>
{% endblock %}