budgeting_app/app/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'app'

urlpatterns = [
    path('', views.dashboard_view, name="dashboard"),
    path('dashboard-delete-transactions', csrf_exempt(views.dashboard_delete_transactions), name="dashboard_delete_transactions"),
    path('dashboard-get-categories', csrf_exempt(views.dashboard_get_categories), name="dashboard_get_categories"),
    path('dashboard-edit-transaction', views.dashboard_edit_transaction, name="dashboard_edit_transaction"),
    path('dashboard-get-chart', csrf_exempt(views.dashboard_get_chart), name="dashboard_get_chart"),
    path('transactions/', views.transactions_view, name="transactions"),
    path('categories/', views.categories_view, name="categories"),
    path('summaries/', views.summaries_view, name="summaries"),
    path('create-category', csrf_exempt(views.create_category), name="create_category"),
    path('edit-category', csrf_exempt(views.edit_category), name="edit_category"),
    path('delete-category', csrf_exempt(views.delete_category), name="delete_category"),
    path('edit-budget', csrf_exempt(views.edit_budget), name="edit_budget"),
    path('get-budget', csrf_exempt(views.get_budget), name="get_budget"),
    path('set-date-range', csrf_exempt(views.set_date_range), name="set_date_range"),
    path('get-pie-chart', csrf_exempt(views.get_pie_chart), name="get_pie_chart"),
    path('set-sort-date', csrf_exempt(views.set_sort_date), name="set_sort_date"),
    path('set-sort-amount', csrf_exempt(views.set_sort_amount), name="set_sort_amount"),
    path('search-transactions', csrf_exempt(views.search_transactions), name="search_transactions"),
    path('get-expenses', csrf_exempt(views.get_expenses), name="get_expenses"),
    path('settings', views.settings_view, name="settings"),
    path('get-rates', csrf_exempt(views.get_rates), name="get_rates"),
    path('change-pfp', csrf_exempt(views.change_pfp), name="change_pfp"),
    path('delete_user', views.delete_user, name="delete_user"),
    path('export-csv', views.export_csv, name="export_csv"),
]

budgeting_app/budgeting_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('app/', include("app.urls")),
    path('users/', include("users.urls")),
]

budgeting_app/app/templates/partials/_budget_history_modal.html
<div class="modal fade" id="historyModalToggle" aria-hidden="true" aria-labelledby="historyModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
        <div class="modal-header d-flex align-items-center justify-content-between">
            <h1 class="modal-title fs-5" id="historyModalToggleLabel">Expense History</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <div class="modal-body">
                <div class="table-responsive px-2">
                    <table class="table table-sm">
                    <thead class="fs-6">
                        <tr>
                            <th scope="col">Type</th>
                            <th scope="col" class="d-flex gap-1 align-items-center"><div>Amount</div></th>
                            <th scope="col">Category</th>
                            <th scope="col" class="d-flex gap-1 align-items-center"><div>Date</div></th>
                            <th scope="col">Comment</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody class="fs-6" id="historyTable">

                    </tbody>
                    </table>
                </div>
                <button class="btn btn-primary" id="seeMoreHistory">See more</button>
            </div>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_category_modal.html
<div class="modal fade" id="expenseCategoryToggle" aria-hidden="true" aria-labelledby="expenseCategoryToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header d-flex align-items-center justify-content-between">
            <h1 class="modal-title fs-5" id="expenseCategoryToggleLabel">Creating category</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="modal-body">
                <input type="hidden" name="category_type" id="category_type1" value="Expense">
                <div class="form-floating mb-3">
                    <input class="form-control" type="text" name="title" id="title1" required>
                    <label for="title1">Title</label>
                </div>

                <div class="mb-3">
                    <p>Choose an icon:</p>
                    <div id="iconsContainer" class="d-flex flex-wrap gap-2 overflow-y-auto" style="max-height: 350px;">
                        {% for icon in icons %}
                        <div data-bs-icon="{{ icon }}" class="mb-1 icon rounded-circle bg-secondary d-flex justify-content-center align-items-center" style="width:60px; height:60px;">
                            <i class="lni {{ icon }} text-white fs-3"></i>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="createExpenseCategory" class="btn btn-primary">Create</button>
            </div>
        </form>
      </div>
    </div>
</div>

<div class="modal fade" id="incomeCategoryToggle" aria-hidden="true" aria-labelledby="incomeCategoryToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header d-flex align-items-center justify-content-between">
            <h1 class="modal-title fs-5" id="incomeCategoryToggleLabel">Creating category</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="modal-body">
                <input type="hidden" name="category_type" id="category_type2" value="Income">
                <div class="form-floating mb-3">
                    <input class="form-control" type="text" name="title" id="title2" required>
                    <label for="title2">Title</label>
                </div>

                <div class="mb-3">
                    <p class="mb-2">Choose an icon:</p>
                    <div id="iconsContainer" class="d-flex flex-wrap gap-2 overflow-y-auto" style="max-height: 350px;">
                        {% for icon in icons %}
                        <div data-bs-icon="{{ icon }}" class="mb-1 icon rounded-circle bg-secondary d-flex justify-content-center align-items-center" style="width:60px; height:60px;">
                            <i class="lni {{ icon }} text-white fs-3"></i>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="createIncomeCategory" class="btn btn-primary">Create</button>
            </div>
        </form>
      </div>
    </div>
</div>

budgeting_app/app/templates/partials/_choose_pfp_modal.html
<div class="modal fade" id="choosePfpModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="choosePfpModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="choosePfpModalLabel">Choose a profile picture</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
</div>

budgeting_app/app/templates/partials/_custom_date_modal.html
<div class="modal fade" id="customDateModal" aria-hidden="true" aria-labelledby="customDateModalLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center justify-content-between">
                <h1 class="modal-title fs-5" id="customDateModalLabel">Choose custom dates</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="date" class="mb-1">Starting date:</label><br>
                    <input type="date" class="form-control" name="startDate" id="startDate" max="{{ current_day_min }}" min="{{ earliest_day_min }}" value="{{ customStart }}" required>
                </div>
                <div class="mb-3">
                    <label for="date" class="mb-1">Ending date:</label><br>
                    <input type="date" class="form-control" name="endDate" id="endDate" max="{{ current_day_min }}" min="{{ earliest_day_min }}" value="{{ customEnd }}" required>
                </div>
            </div>
            <div class="modal-footer">
                <button id="submitCustomDates" class="btn btn-primary">Set dates</button>
            </div>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_delete_account_modal.html
<div class="modal fade" id="deleteAccountModal" aria-hidden="true" aria-labelledby="deleteAccountModalLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header d-flex align-items-center justify-content-between">
            <h1 class="modal-title fs-5" id="deleteAccountModalLabel">Are you sure you want to go? 😢</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <div class="modal-body px-4" id="modal-body">
                <p>By deleting your account, you will lose access to:</p>
                <ul>
                    <li style="list-style: disc;">Your personalized settings and preferences</li>
                    <li style="list-style: disc;">All transactions and custom-made categories</li>
                    <li style="list-style: disc;">All logs and graphs with your data</li>
                </ul>
                <p>Remember, once you delete your account, there's no going back. 😔</p>
            </div>
            <div class="modal-footer d-flex justify-content-between">
                <form method="post" action="{% url 'app:delete_user' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" id="deleteAccount">Delete forever</button>
                </form>
                <button class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">Keep my account</button>
            </div>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_edit_budget_modal.html
<div class="modal fade" id="editBudgetModal" aria-hidden="true" aria-labelledby="editBudgetModalLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center justify-content-between">
                <h1 class="modal-title fs-5" id="editBudgetModalLabel">Budget settings</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div>
                {% csrf_token %}
                <div class="modal-body">
                    <p class="mb-2 text-black-50">Enter your monthly budget</p>
                    <div class="d-flex align-items-center gap-2">
                        <select class="form-select" id="currency" name="currency" aria-label="Choose currency" style="width: auto;">
                            <option value="USD">USD</option>
                            <option value="EUR">EUR</option>
                            <option value="MKD">MKD</option>
                        </select>
                        <div class="form-floating mb-3" style="width: 100%;">
                            <input class="form-control" type="number" min="0" name="shownBudget" id="shownBudget" step="0.01" required>
                            <input class="form-control" type="hidden" min="0" name="budget" id="budget" step="0.01" required>
                            <label for="title">Budget</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {% if request.session.new_user %}<button id="noBudgetBtn" class="btn btn-secondary">Not now</button>{% endif %}
                    <button id="editBudgetBtn" class="btn btn-primary">Set budget</button>
                </div>
            </div>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_edit_category_modal.html
<div class="modal fade" id="editCategoryModal" aria-hidden="true" aria-labelledby="editCategoryModalLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center justify-content-between">
                <h1 class="modal-title fs-5" id="editCategoryModalLabel">Editing category</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <input type="hidden" name="id" id="id">
                    <input type="hidden" name="category_type" id="category_type" value="Expense">
                    <div class="form-floating mb-3">
                        <input class="form-control" type="text" name="title" id="title" required>
                        <label for="title">Title</label>
                    </div>

                    <div class="mb-3">
                        <p>Choose an icon:</p>
                        <div id="iconsContainer" class="d-flex flex-wrap gap-2">
                            {% for icon in icons %}
                            <div data-bs-icon="{{ icon }}" class="mb-1 icon rounded-circle bg-secondary d-flex justify-content-center align-items-center" style="width:60px; height:60px;">
                                <i class="lni {{ icon }} text-white fs-3"></i>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="editCategoryBtn" class="btn btn-primary">Finish</button>
                    <button id="deleteCategoryBtn" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_edit_modal.html
<div class="modal fade" id="editModalToggle" aria-hidden="true" aria-labelledby="editModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header d-flex align-items-center justify-content-between">
            <h1 class="modal-title fs-5" id="editModalToggleLabel">Editing transaction</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'app:dashboard_edit_transaction' %}" method="post">
            {% csrf_token %}
            <div class="modal-body" id="modal-body">
                <input type="hidden" name="id" id="id">
                <input type="hidden" name="transaction_type" id="transaction_type">
                <div class="d-flex align-items-center gap-2">
                    <select class="form-select" id="currency" name="currency" aria-label="Choose currency" style="width: auto;">
                        <option value="USD">USD</option>
                        <option value="EUR">EUR</option>
                        <option value="MKD">MKD</option>
                    </select>
                    <div class="form-floating mb-3" style="width: 100%;">
                        <input class="form-control" type="number" step="0.01" name="shownAmount" id="shownAmount">
                        <label for="shownAmount">Amount</label>
                    </div>
                    <input class="form-control" type="hidden" step="0.01" name="amount" id="amount">
                </div>

                <div class="form-floating mb-3">
                    <select class="form-select" id="category" name="category" aria-label="Choose a category">
                        <option selected>Choose a category</option>
                    </select>
                    <label for="floatingSelect">Category</label>
                </div>

                <div class="mb-3">
                    <label for="date" class="mb-1">Date of expense:</label><br>
                    <input type="datetime-local" class="form-control" name="date" id="date" max="{{ current_day }}" min="{{ earliest_day }}">
                </div>

                <div class="form-floating mb-3">
                    <textarea class="form-control" placeholder="Comments" id="comment" name="comment" style="height: 100px"></textarea>
                    <label for="comment">Comments</label>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary">Save changes</button>
            </div>
        </form>
        </div>
    </div>
</div>

budgeting_app/app/templates/partials/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="mt-4 alert alert-{{ message.tags }} alert-dismissible" {% endif %}>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

budgeting_app/app/templates/partials/_transaction_modal.html
<div class="modal fade" id="typeModelToggle" aria-hidden="true" aria-labelledby="typeModelToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="typeModelToggleLabel">Type of transaction:</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex justify-content-around">
        <button class="btn btn-primary" data-bs-target="#expenseModalToggle" data-bs-toggle="modal">Expense</button>
        <button class="btn btn-primary" data-bs-target="#incomeModalToggle" data-bs-toggle="modal">Income</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="expenseModalToggle" aria-hidden="true" aria-labelledby="expenseModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <button class="btn rounded-circle me-2" data-bs-target="#typeModelToggle" data-bs-toggle="modal">
            <i class="lni lni-arrow-left mt-2"></i>
          </button>
          <h1 class="modal-title fs-5" id="expenseModalToggleLabel">Add Expense</h1>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% if request.path == "/app/"  %}{% url 'app:dashboard' %}{% else %}{% url 'app:transactions' %}{% endif %}" method="post">
          {% csrf_token %}
          <div class="modal-body">
              <input type="hidden" name="transaction_type" value="Expense">
              <div class="d-flex align-items-center gap-2">
                <select class="form-select" id="currencyExpense" name="currency" aria-label="Choose currency" style="width: auto;">
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                    <option value="MKD">MKD</option>
                </select>
                <div class="form-floating mb-3" style="width: 100%;">
                    <input class="form-control" type="number" step="0.01" name="shownAmount" id="shownAmountExpense">
                    <label for="shownAmountExpense">Amount</label>
                </div>
                <input class="form-control" type="hidden" step="0.01" name="amount" id="amountExpense">
              </div>

              <div class="form-floating mb-3">
                <select class="form-select" id="category" name="category" aria-label="Choose a category">
                  <option selected>Choose a category</option>
                  {% for category in defaultExpenseCategories %}
                    <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                  {% for category in userExpenseCategories %}
                    <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                </select>
                <label for="floatingSelect">Category</label>
              </div>

              <div class="mb-3">
                <label for="date" class="mb-1">Date of expense:</label><br>
                <input type="datetime-local" class="form-control" name="date" id="date" max="{{ current_day }}" min="{{ earliest_day }}" value="{{ current_day }}">
              </div>

              <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="Comments" id="comment" name="comment" style="height: 100px"></textarea>
                <label for="comment">Comments</label>
              </div>
          </div>
          <div class="modal-footer">
              <button class="btn btn-primary">Add Expense</button>
          </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="incomeModalToggle" aria-hidden="true" aria-labelledby="incomeModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <button class="btn rounded-circle me-2" data-bs-target="#typeModelToggle" data-bs-toggle="modal">
            <i class="lni lni-arrow-left mt-2"></i>
          </button>
          <h1 class="modal-title fs-5" id="incomeModalToggleLabel">Add Income</h1>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% if request.path == "/app/"  %}{% url 'app:dashboard' %}{% else %}{% url 'app:transactions' %}{% endif %}" method="post">
          {% csrf_token %}
          <div class="modal-body">
              <input type="hidden" name="transaction_type" value="Income">
              <div class="d-flex align-items-center gap-2">
                <select class="form-select" id="currencyIncome" name="currency" aria-label="Choose currency" style="width: auto;">
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                    <option value="MKD">MKD</option>
                </select>
                <div class="form-floating mb-3" style="width: 100%;">
                    <input class="form-control" type="number" step="0.01" name="shownAmount" id="shownAmountIncome">
                    <label for="shownAmountIncome">Amount</label>
                </div>
                <input class="form-control" type="hidden" step="0.01" name="amount" id="amountIncome">
              </div>

              <div class="form-floating mb-3">
                <select class="form-select" id="category" name="category" aria-label="Choose a category">
                  <option selected>Choose a category</option>
                  {% for category in defaultIncomeCategories %}
                    <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                  {% for category in userIncomeCategories %}
                    <option value="{{category}}">{{category}}</option>
                  {% endfor %}
                </select>
                <label for="floatingSelect">Category</label>
              </div>

              <div class="mb-3">
                <label for="date" class="mb-1">Date of income:</label><br>
                <input type="datetime-local" class="form-control" name="date" id="date" max="{{ current_day }}" min="{{ earliest_day }}" value="{{ current_day }}">
              </div>

              <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="Comments" id="comment" name="comment" style="height: 100px"></textarea>
                <label for="comment">Comments</label>
              </div>
          </div>
          <div class="modal-footer">
              <button class="btn btn-primary">Add Income</button>
          </div>
      </form>
    </div>
  </div>
</div>