budgeting_app/app/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'app'

urlpatterns = [
    path('', views.dashboard_view, name="dashboard"),
    path('dashboard-delete-transactions', csrf_exempt(views.dashboard_delete_transactions), name="dashboard_delete_transactions"),
    path('dashboard-get-categories', csrf_exempt(views.dashboard_get_categories), name="dashboard_get_categories"),
    path('dashboard-edit-transaction', views.dashboard_edit_transaction, name="dashboard_edit_transaction"),
    path('dashboard-get-chart', csrf_exempt(views.dashboard_get_chart), name="dashboard_get_chart"),
    path('transactions/', views.transactions_view, name="transactions"),
    path('categories/', views.categories_view, name="categories"),
    path('summaries/', views.summaries_view, name="summaries"),
    path('create-category', csrf_exempt(views.create_category), name="create_category"),
    path('edit-category', csrf_exempt(views.edit_category), name="edit_category"),
    path('delete-category', csrf_exempt(views.delete_category), name="delete_category"),
    path('edit-budget', csrf_exempt(views.edit_budget), name="edit_budget"),
    path('get-budget', csrf_exempt(views.get_budget), name="get_budget"),
    path('set-date-range', csrf_exempt(views.set_date_range), name="set_date_range"),
    path('get-pie-chart', csrf_exempt(views.get_pie_chart), name="get_pie_chart"),
    path('set-sort-date', csrf_exempt(views.set_sort_date), name="set_sort_date"),
    path('set-sort-amount', csrf_exempt(views.set_sort_amount), name="set_sort_amount"),
    path('search-transactions', csrf_exempt(views.search_transactions), name="search_transactions"),
    path('get-expenses', csrf_exempt(views.get_expenses), name="get_expenses"),
    path('settings', views.settings_view, name="settings"),
    path('get-rates', csrf_exempt(views.get_rates), name="get_rates"),
    path('change-pfp', csrf_exempt(views.change_pfp), name="change_pfp"),
    path('delete_user', views.delete_user, name="delete_user"),
    path('export-csv', views.export_csv, name="export_csv"),
]

budgeting_app/budgeting_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('app/', include("app.urls")),
    path('users/', include("users.urls")),
]

budgeting_app/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.landing_view, name="landing"),
]

budgeting_app/users/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

budgeting_app/landing/models.py
from django.db import models

# Create your models here.

budgeting_app/landing/views.py
from django.shortcuts import render

# Create your views here.
def landing_view(request):
    return render(request, "landing/landing.html")

budgeting_app/landing/templates/landing/landing.html
{% extends 'landing/layout.html' %}
{% block title %}
    Dollabro
{% endblock %}

{% block content %}
<div class="top__wrapper">
    <nav class="container d-flex justify-content-between align-items-center py-3 text-white">
        <div class="logo d-flex gap-1 align-items-center">
            <i class="lni lni-coin fs-2"></i>
            <h5 class="mb-0 fs-2">Dollabro</h5>
        </div>
        <div class="nav__btns d-flex gap-3">
            <a href="{% url 'users:register' %}" class="btn btn-secondary register_btn px-3 py-2">Register</a>
            <a href="{% url 'users:login' %}" class="btn btn-primary login__btn px-3 py-2">Login</a>
        </div>
    </nav>
    <header class="container d-flex flex-column flex-lg-row align-items-center gap-5 text-white">
        <div class="text">
            <h1 class="mb-4">Stay on Track the Easy Way with <span id="header__dollabro">Dollabro</span>!</h1>
            <p class="mb-5">Effortless tool for tracking and analysing your transactions, settings budgets and managing finances. Stay in control and reach financial goals with ease all in one place.</p>
            <a href="{% url 'users:login' %}" class="btn btn-primary login__btn px-4 py-3 d-flex gap-2 align-items-center"><span>Open Dollabro</span><i class="lni lni-chevron-right"></i></a>
        </div>
        <div class>
            <img src="https://i.imgur.com/82xrnr1.png" alt="hero picture">
        </div>
    </header>
</div>
<section id="features" class="container d-flex flex-column align-items-center">
    <h1 class="features__heading text-center">What Can Dollabro Do?</h1>
    <div class="features__container d-flex flex-column flex-md-row flex-nowrap flex-md-wrap gap-3 justify-content-center">
        <div class="card card-yellow text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-stats-up fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Income and Expense Logging</h5>
              <p class="card-text">Effortlessly record and categorize your earnings and spending, helping you maintain a clear overview of your financial situation at all times.</p>
            </div>
        </div>
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-cart-full fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Set and Track Monthly Budget</h5>
              <p class="card-text">Define your monthly spending limits and track your progress in real-time, ensuring you stay within budget and meet your financial goals.</p>
            </div>
        </div>
        <div class="card card-yellow text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-pie-chart fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Data Visualization</h5>
              <p class="card-text">Gain valuable insights into your financial habits with visually engaging charts and graphs that make it easy to understand your spending patterns.</p>
            </div>
        </div>
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-home fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Create and Monitor Categories</h5>
              <p class="card-text">Organize your transactions by creating customizable categories, allowing for better tracking and management of specific expense types.</p>
            </div>
        </div>
        <div class="card card-yellow text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-euro fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Multi-Currency Display</h5>
              <p class="card-text">Seamlessly switch between multiple currencies for viewing your financial data, accommodating both local and international transactions.</p>
            </div>
        </div>
        <div class="card text-center shadow-sm">
            <div class="card-body">
                <i class="lni lni-empty-file fs-2 mb-3 mt-2"></i>
              <h5 class="card-title">Data Export Functionality</h5>
              <p class="card-text">Easily download your financial records in various formats, making it convenient to analyze or share your data with others when needed.</p>
            </div>
        </div>
    </div>
</section>
<section id="details" class="container d-flex flex-column align-items-center">
    <h1 class="details__heading text-center">Why Choose Dollabro?</h1>
    <div class="details__container">
        <div class="card text-center shadow-sm mb-3">
            <div class="card-body">
              <h5 class="card-title">Slick and Simple, Yet Powerful</h5>
              <p class="card-text">A clean, modern interface designed to keep things intuitive while packing a punch under the hood. Manage your money without feeling overwhelmed by features—just what you need, when you need it.</p>
            </div>
        </div>
        <div class="card card-yellow text-center shadow-sm">
            <div class="card-body">
              <h5 class="card-title">Budgeting, Evolved</h5>
              <p class="card-text">Dollabro is built for the future, blending cutting-edge tech with effortless usability. It’s budgeting made smarter, giving you real-time insights and control, whether you’re saving for a goal or tracking expenses.</p>
            </div>
        </div>
        <div class="card text-center shadow-sm">
            <div class="card-body">
              <h5 class="card-title">Lightning-Fast, Always Ready</h5>
              <p class="card-text">Say goodbye to slow loading and clunky dashboards. With Dollabro, everything happens in real-time, ensuring that your finances are always up to date and accessible at the tap of a button.</p>
            </div>
        </div>
    </div>
</section>
<section id="demos">
    <div class="top__wrapper">
        <div id="quickTransaction" class="container">
            <div class="top text-white">
                <h6 class="text_yellow mb-2">QUICK AND SIMPLE TRANSACTION LOGGING</h6>
                <h1>Log your day in a few seconds</h1>
            </div>
            <div class="content d-flex flex-column flex-lg-row align-items-start mt-5" style="gap: 5rem;">
                <div style="max-width: 400px;">
                    <ul class="text-white ms-0 ps-4 fs-5">
                        <li class="mb-3">Add transactions quickly from anywhere in your application.</li>
                        <li class="mb-3">Analyze real-time trends and changes with interactive charts that are easy to understand.</li>
                        <li class="mb-3">Drill down on your spending habits by having all necessary information displayed in an elegant way.</li>
                    </ul>
                    <a style="width:fit-content;" href="{% url 'users:register' %}" class="btn join__btn d-flex gap-2 align-items-center fw-bold mt-5"><span>Join Dollabro Now</span><i class="lni lni-chevron-right"></i></a>
                </div>
                <div class="w-100">
                    <iframe src="https://player.vimeo.com/video/1016524862?autoplay=1&amp;autopause=0&amp;loop=1&amp;muted=1&amp;title=0&amp;byline=0&amp;portrait=0&amp;controls=0&amp;app_id=58479" frameborder="0" allow="autoplay"></iframe>
                </div>
            </div>
        </div>
    </div>
    <div id="searchDates" class="container">
        <div class="top">
            <h6 class="text_yellow_light mb-2">FULLY CUSTOMIZABLE LOOKUPS</h6>
            <h1>Be in control of what you see</h1>
        </div>
        <div class="content d-flex flex-column flex-lg-row align-items-start mt-5" style="gap: 5rem;">
            <div class="w-100">
                <iframe src="https://player.vimeo.com/video/1016527685?autoplay=1&amp;autopause=0&amp;loop=1&amp;muted=1&amp;title=0&amp;byline=0&amp;portrait=0&amp;controls=0&amp;app_id=58479" frameborder="0" allow="autoplay"></iframe>
            </div>
            <div style="max-width: 400px;">
                <ul class="ms-0 ps-4 fs-5">
                    <li class="mb-3">Look up your transactions by amount, type, category and comment.</li>
                    <li class="mb-3">Set custom date ranges for a more specific analysis of your income and expenses.</li>
                    <li class="mb-3">Always see relevant information and charts about your transactions based on your filtering, at any time.</li>
                </ul>
                <a style="width:fit-content;" href="{% url 'users:register' %}" class="btn join__btn_light d-flex gap-2 align-items-center fw-bold mt-5"><span>Join Dollabro Now</span><i class="lni lni-chevron-right"></i></a>
            </div>
        </div>
    </div>
    <div class="top__wrapper">
        <div id="currencyDemo" class="container">
            <div class="top text-white">
                <h6 class="text_yellow mb-2">SWITCH BETWEEN POPULAR CURRENCIES</h6>
                <h1>Always work in your preferred currency</h1>
            </div>
            <div class="content d-flex flex-column flex-lg-row align-items-start mt-5" style="gap: 5rem;">
                <div style="max-width: 400px;">
                    <ul class="text-white ms-0 ps-4 fs-5">
                        <li class="mb-3">Add transactions in any currency at any time.</li>
                        <li class="mb-3">Choose which currency to be displayed everywhere in your application.</li>
                        <li class="mb-3">Rapid currency conversions in real-time for greatest accuracy.</li>
                    </ul>
                    <a style="width:fit-content;" href="{% url 'users:register' %}" class="btn join__btn d-flex gap-2 align-items-center fw-bold mt-5"><span>Join Dollabro Now</span><i class="lni lni-chevron-right"></i></a>
                </div>
                <div class="w-100">
                    <iframe src="https://player.vimeo.com/video/1016549480?autoplay=1&amp;autopause=0&amp;loop=1&amp;muted=1&amp;title=0&amp;byline=0&amp;portrait=0&amp;controls=0&amp;app_id=58479" frameborder="0" allow="autoplay"></iframe>
                </div>
            </div>
        </div>
    </div>
    <div id="categoriesDemo" class="container">
        <div class="top">
            <h6 class="text_yellow_light mb-2">INFINITE LABELS FOR YOUR TRANSACTIONS</h6>
            <h1>Create as many categories as you need</h1>
        </div>
        <div class="content d-flex flex-column flex-lg-row align-items-start mt-5" style="gap: 5rem;">
            <div class="w-100">
                <iframe src="https://player.vimeo.com/video/1016563711?autoplay=1&amp;autopause=0&amp;loop=1&amp;muted=1&amp;title=0&amp;byline=0&amp;portrait=0&amp;controls=0&amp;app_id=58479" frameborder="0" allow="autoplay"></iframe>
            </div>
            <div style="max-width: 400px;">
                <ul class="ms-0 ps-4 fs-5">
                    <li class="mb-3">Choose from many useful pre-defined categories.</li>
                    <li class="mb-3">Create your own categories that you can utilize immediately for your transactions.</li>
                    <li class="mb-3">Choose from a wide variety of icons for your categories.</li>
                </ul>
                <a style="width:fit-content;" href="{% url 'users:register' %}" class="btn join__btn_light d-flex gap-2 align-items-center fw-bold mt-5"><span>Join Dollabro Now</span><i class="lni lni-chevron-right"></i></a>
            </div>
        </div>
    </div>
    <script src="https://player.vimeo.com/api/player.js"></script>
</section>
<footer class="py-4 text-white">
    <p class="mb-0 text-center">Made by Petar Avramovikj ©2024</p>
</footer>
{% endblock %}

budgeting_app/landing/templates/landing/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Budgeting App
        {% endblock %}
    </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>